SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/Candidate_AtharvaBhatkhalkar__c.object-meta.xml
<CustomObject>
    <description>Fields -
Following are the fields need to be created on object Candidate. A trainee will create the following fields with the mentioned Label name and appropriate data type. Also, refer to the Required field column for each field.</description>
    <label>Candidate_AtharvaBhatkhalkar</label>
    <nameField>
        <label>Candidate_AtharvaBhatkhalkar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate_AtharvaBhatkhalkar</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/Application_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Date__c</fullName>
    <description>It should accept date.</description>
    <inlineHelpText>kindly input the date</inlineHelpText>
    <label>Application Date</label>
    <type>Date</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>One should enter only valid email address</description>
    <inlineHelpText>kindly give your valid Email.</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/Expected_Salary__c.field-meta.xml
<CustomField>
    <fullName>Expected_Salary__c</fullName>
    <description>It should accept numerical value in dollar format</description>
    <label>Expected Salary</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Text field
Should only accept 15 characters.</description>
    <inlineHelpText>Kindly enter your first name here.</inlineHelpText>
    <label>First Name</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/JOB__c.field-meta.xml
<CustomField>
    <fullName>JOB__c</fullName>
    <description>It should be able to relate a candidate to a job</description>
    <label>Job_AtharvaBhatkhalkar</label>
    <referenceTo>Job_AtharvaBhatkhalkar__c</referenceTo>
    <relationshipLabel>Candidate_AtharvaBhatkhalkar</relationshipLabel>
    <relationshipName>Candidate_AtharvaBhatkhalkar</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Text field
Should only accept 15 characters.</description>
    <inlineHelpText>Kindly enter your last name.</inlineHelpText>
    <label>Last Name</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>User should be able to accept the value from this values : Applied, Interviewed, Reject, Hired.</description>
    <inlineHelpText>kindly select your status.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewed</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Deactivate_Triggers__c/Deactivate_Triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Deactivate and Activate Triggers</description>
    <label>Deactivate_Triggers</label>
</CustomObject>

SalesforceTraining/force-app/main/default/objects/Deactivate_Triggers__c/fields/Deactivate_ActivateTriggers__c.field-meta.xml
<CustomField>
    <fullName>Deactivate_ActivateTriggers__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deactivate/ActivateTriggers</label>
    <type>Checkbox</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/Job_AtharvaBhatkhalkar__c.object-meta.xml
<CustomObject>
    <description>Fields -
Following are the fields need to be created on object Job. A trainee will create the following fields with the mentioned Label name and appropriate data type.</description>
    <label>Job_AtharvaBhatkhalkar</label>
    <nameField>
        <label>Job_AtharvaBhatkhalkar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_AtharvaBhatkhalkar</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field should have only two either or values (true/false)
If it has one value it means a job is active
If it has another value it means a job is not active</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Hired_Applicants__c.field-meta.xml
<CustomField>
    <fullName>Hired_Applicants__c</fullName>
    <description>This field indicates the count of the total Hired candidate has applied to this job.
It should be a numeric field and must be calculated automatically as any candidate is hired for a job( Candidate status = ‘Hired’);</description>
    <label>Hired Applicants</label>
    <summaryFilterItems>
        <field>Candidate_AtharvaBhatkhalkar__c.Status__c</field>
        <operation>equals</operation>
        <value>Hired</value>
    </summaryFilterItems>
    <summaryForeignKey>Candidate_AtharvaBhatkhalkar__c.JOB__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field indicates the relation of job record to the Contact record.</description>
    <label>Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job_AtharvaBhatkhalkar</relationshipLabel>
    <relationshipName>Job_AtharvaBhatkhalkar1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Number_of_Positions__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Positions__c</fullName>
    <description>This field indicates how many numbers of positions are available for this position
It should accept only numeric values up to 10 digits and not any text value.</description>
    <inlineHelpText>kindly enter the number of positions</inlineHelpText>
    <label>Number of Positions</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Qualification_Required__c.field-meta.xml
<CustomField>
    <fullName>Qualification_Required__c</fullName>
    <label>Qualification_Required</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Job_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Bcom</fullName>
            </value>
            <value>
                <fullName>MBA</fullName>
            </value>
            <value>
                <fullName>BBA</fullName>
            </value>
            <value>
                <fullName>BSC</fullName>
            </value>
            <value>
                <fullName>BTech.</fullName>
            </value>
            <value>
                <fullName>MSC</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SalesforceTraining/force-app/main/default/classes/TestMethodForCandidateTrigger.cls
/********************************************************************** 
Name: TestMethodForCandidateTrigger 
Copyright © 2019 Enzigma Company Inc. 
====================================================== 
====================================================== 
Purpose: This class is used for testing all the candidate
		Trigger.
------- 
====================================================== 
====================================================== 
History 
------- 
VERSION AUTHOR DATE DETAIL FEATURES/CSR/TTP 
1.0 - Atharva Ravindra Bhatkhalkar 03/04/2009 INITIAL DEVELOPMENT CSR:  
***********************************************************************/ 


@isTest
public class TestMethodForCandidateTrigger {
/*******************************************************************
Purpose: This method is written for the data required for testing 
		purpose.
********************************************************************/
    @testSetup public static void testSetup() {
        Deactivate_Triggers__c objOfDeactivateTriggers = new Deactivate_Triggers__c();
        objOfDeactivateTriggers.Deactivate_ActivateTriggers__c=true;
        insert objOfDeactivateTriggers;
        system.assertEquals(objOfDeactivateTriggers.Deactivate_ActivateTriggers__c, true);
        
     
	}
 /*******************************************************************
Purpose: This method checks for the salary field if it is empty then 
		it gives error.
Throws [Exceptions]: Expected Salary field is missing
********************************************************************/
   
    @isTest
    public static void testMethodForSalaryFieldMissing(){
        try{
            Contact objContact = new Contact(LastName='Test-Enzigma-Contact');
            insert objContact;
            Job_AtharvaBhatkhalkar__c objOfjob = new Job_AtharvaBhatkhalkar__c(Number_of_Positions__c=20,Manager__c=objContact.id,Active__c=true,
                                                                               Qualification_Required__c='MBA');
            insert objOfjob;
            Candidate_AtharvaBhatkhalkar__c objForItr=  new Candidate_AtharvaBhatkhalkar__c(First_Name__c='Anuaja',Last_Name__c='Joshi', Email__c='anuja@user.com',
                                                                                            Status__c='Applied',Expected_Salary__c=NULL, JOB__c=objOfjob.Id);
            insert objForItr;
            
            system.assertNotEquals(objForItr.Id, NULL);
            
        }
        catch(Exception e){
            System.assert(e.getMessage().contains('Expected Salary field is missing'));
        }
    }
    
/*******************************************************************
Purpose: This Method checks that the job applied is active or not,
		if it is inactive then the value is not inserted and it gives 
		the	error.
Throws [Exceptions]: Applied job is inactive
********************************************************************/

    @isTest
    public static void testMethodForJobAppliedIsInactive(){
        
        try{
            Contact objContact = new Contact(LastName='Test-Enzigma-Contact');
            insert objContact;
            Job_AtharvaBhatkhalkar__c objOfjob = new Job_AtharvaBhatkhalkar__c(Number_of_Positions__c=20,
                                                                               Manager__c=objContact.id,
                                                                               Active__c=false,
                                                                               Qualification_Required__c='MBA');
            insert objOfjob;
            Candidate_AtharvaBhatkhalkar__c objForItr=  new Candidate_AtharvaBhatkhalkar__c(First_Name__c='Anutja',
                                                                                            Last_Name__c='Joshi', 
                                                                                            Email__c='anuja@user.com',
                                                                                            Status__c='Applied',
                                                                                            Expected_Salary__c=NULL, 
                                                                                            JOB__c=objOfjob.Id);
            insert objForItr; 
            system.assertNotEquals(objForItr.id, null);
        }
        catch(Exception e){
            system.assert(e.getMessage().contains('Applied job is inactive'));
        }
        
        
    }
/*******************************************************************
Purpose: This method checks that if the application date is equal to the
		created date or not.
********************************************************************/

    @isTest
    public static void testMethodForReplacingCreatedDateWithSystemDate(){
         Contact objContact = new Contact(LastName='Test-Enzigma-Contact');
            insert objContact;
            Job_AtharvaBhatkhalkar__c objOfjob = new Job_AtharvaBhatkhalkar__c(Number_of_Positions__c=20,
                                                                               Manager__c=objContact.id,
                                                                               Active__c=true,
                                                                               Qualification_Required__c='MBA');
            insert objOfjob;
            Candidate_AtharvaBhatkhalkar__c objForItr=  new Candidate_AtharvaBhatkhalkar__c(First_Name__c='Anuja',
                                                                                            Last_Name__c='Joshi', 
                                                                                            Email__c='anuja@user.com',
                                                                                            Application_Date__c=Date.newInstance(2019, 03, 15),
                                                                                            Status__c='Applied',
                                                                                            Expected_Salary__c=12341, 
                                                                                            JOB__c=objOfjob.Id);
            insert objForItr; 

        
        	Candidate_AtharvaBhatkhalkar__c objOfCandidate = [SELECT id,Application_Date__c FROM Candidate_AtharvaBhatkhalkar__c
                                                             WHERE First_Name__c='Anuja'];
        	objOfCandidate.Application_Date__c=system.today();
        	system.debug(objOfCandidate.Application_Date__c);
        	update objOfCandidate;
        	system.debug(objOfCandidate);
        	system.assertEquals(objOfCandidate.Application_Date__c, system.today());
        
    }
    
   /* @isTest
    public static void testMethodForSendingMailToHiredCandidate(){
         Contact objContact = new Contact(LastName='Test-Enzigma-Contact');
            insert objContact;
            Job_AtharvaBhatkhalkar__c objOfjob = new Job_AtharvaBhatkhalkar__c(Number_of_Positions__c=20,
                                                                               Manager__c=objContact.id,
                                                                               Active__c=true,
                                                                               Qualification_Required__c='MBA');
            insert objOfjob;
            Candidate_AtharvaBhatkhalkar__c objForItr=  new Candidate_AtharvaBhatkhalkar__c(First_Name__c='Anuja',
                                                                                            Last_Name__c='Joshi', 
                                                                                            Email__c='anuja@user.com',
                                                                                            Status__c='Applied',
                                                                                            Expected_Salary__c=12341, 
                                                                                            JOB__c=objOfjob.Id);
            insert objForItr; 
        
        	Candidate_AtharvaBhatkhalkar__c objOfCandidateForEmail = [SELECT id,Status__c,Email__c FROM Candidate_AtharvaBhatkhalkar__c
                                                                     WHERE id=:objForItr.Id];
        
        	objOfCandidateForEmail.Status__c='Hired';
        	update objOfCandidateForEmail;
        	if(objOfCandidateForEmail.Status__c)
    }*/
/*******************************************************************
Purpose: This test method checks that if hired applicants are equal to 
		the total number of positions or not. If yes then it changes 
		the status of job active to inactive.
********************************************************************/

    
   		  @isTest
    public static void testMethodForSettingStatusToInactive(){
         Contact objContact = new Contact(LastName='Test-Enzigma-Contact');
            insert objContact;
            Job_AtharvaBhatkhalkar__c objOfjob = new Job_AtharvaBhatkhalkar__c(Number_of_Positions__c=1,
                                                                               
                                                                               Manager__c=objContact.id,
                                                                               Active__c=true,
                                                                               Qualification_Required__c='MBA');
            insert objOfjob;
            Candidate_AtharvaBhatkhalkar__c objForItr=  new Candidate_AtharvaBhatkhalkar__c(First_Name__c='Anuja',
                                                                                            Last_Name__c='Joshi', 
                                                                                            Email__c='anuja@user.com',
                                                                                            Application_Date__c=Date.newInstance(2019, 03, 15),
                                                                                            Status__c='Hired',
                                                                                            Expected_Salary__c=12341, 
                                                                                            JOB__c=objOfjob.Id);
            insert objForItr; 

			Job_AtharvaBhatkhalkar__c objOfJobForQuery = [SELECT id,Hired_Applicants__c,Number_of_Positions__c FROM Job_AtharvaBhatkhalkar__c
                                                  WHERE id = :objOfjob.id];
        	
        if(objOfJobForQuery.Hired_Applicants__c == objOfJobForQuery.Number_of_Positions__c-1){
            objOfJobForQuery.Active__c=false;
            update objOfJobForQuery;
            System.assertEquals(objOfJobForQuery.Active__c, false);
        }
        
    }
}