SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/Candidate_AtharvaBhatkhalkar__c.object-meta.xml
<CustomObject>
    <description>Fields -
Following are the fields need to be created on object Candidate. A trainee will create the following fields with the mentioned Label name and appropriate data type. Also, refer to the Required field column for each field.</description>
    <label>Candidate_AtharvaBhatkhalkar</label>
    <nameField>
        <label>Candidate_AtharvaBhatkhalkar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate_AtharvaBhatkhalkar</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/Application_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Date__c</fullName>
    <description>It should accept date.</description>
    <inlineHelpText>kindly input the date</inlineHelpText>
    <label>Application Date</label>
    <type>Date</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Add a list of the following country: Australia, India, United States</description>
    <inlineHelpText>kindly select any</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <description>Should accept the</description>
    <inlineHelpText>kindly give the date of birth</inlineHelpText>
    <label>DOB</label>
    <type>Date</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>One should enter only valid email address</description>
    <inlineHelpText>kindly give your valid Email.</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/Expected_Salary__c.field-meta.xml
<CustomField>
    <fullName>Expected_Salary__c</fullName>
    <description>It should accept numerical value in dollar format</description>
    <label>Expected Salary</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Text field
Should only accept 15 characters.</description>
    <inlineHelpText>Kindly enter your first name here.</inlineHelpText>
    <label>First Name</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/JOB__c.field-meta.xml
<CustomField>
    <fullName>JOB__c</fullName>
    <description>It should be able to relate a candidate to a job</description>
    <label>Job_AtharvaBhatkhalkar</label>
    <referenceTo>Job_AtharvaBhatkhalkar__c</referenceTo>
    <relationshipLabel>Candidate_AtharvaBhatkhalkar</relationshipLabel>
    <relationshipName>Candidate_AtharvaBhatkhalkar</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Text field
Should only accept 15 characters.</description>
    <inlineHelpText>Kindly enter your last name.</inlineHelpText>
    <label>Last Name</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>This field is the name of the job.
User should not enter name but system should create it automatically.
The name should follow this format “JOB-{count}”. Count should be increased automatically for each new job posted(created). For. ex. JOB-001, JOB-002.</description>
    <displayFormat>JOB-{0}</displayFormat>
    <label>Name</label>
    <type>AutoNumber</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <description>It should have fixed values: ‘Mr.’, ‘Ms.’
A user should be able to select any one of the value.</description>
    <inlineHelpText>kindly select any one salutation from list</inlineHelpText>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Ms.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Victoria</fullName>
            </value>
            <value>
                <fullName>Western Australia</fullName>
            </value>
            <value>
                <fullName>Christmas Island</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Gujrat</fullName>
            </value>
            <value>
                <fullName>Madhyapradesh</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>User should be able to accept the value from this values : Applied, Interviewed, Reject, Hired.</description>
    <inlineHelpText>kindly select your status.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewed</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/Job_AtharvaBhatkhalkar__c.object-meta.xml
<CustomObject>
    <description>Fields -
Following are the fields need to be created on object Job. A trainee will create the following fields with the mentioned Label name and appropriate data type.</description>
    <label>Job_AtharvaBhatkhalkar</label>
    <nameField>
        <label>Job_AtharvaBhatkhalkar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_AtharvaBhatkhalkar</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field should have only two either or values (true/false)
If it has one value it means a job is active
If it has another value it means a job is not active</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Certification_Required__c.field-meta.xml
<CustomField>
    <fullName>Certification_Required__c</fullName>
    <label>Certification_Required</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Job_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>PMP (Project Management        Professional)</fullName>
            </value>
            <value>
                <fullName>CMP (Certified Project Manager)</fullName>
            </value>
            <value>
                <fullName>MPM (Master Project Manager)</fullName>
            </value>
            <value>
                <fullName>Sun Certified</fullName>
            </value>
            <value>
                <fullName>SAS</fullName>
            </value>
            <value>
                <fullName>ORACLE</fullName>
            </value>
            <value>
                <fullName>Sybase</fullName>
            </value>
            <value>
                <fullName>Microsoft</fullName>
            </value>
            <value>
                <fullName>CISCO</fullName>
            </value>
            <value>
                <fullName>RedHat</fullName>
            </value>
            <value>
                <fullName>IBM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>This field should accept bold text, italic text, underline text, images.</description>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field indicates the relation of job record to the Contact record.</description>
    <label>Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job_AtharvaBhatkhalkar</relationshipLabel>
    <relationshipName>Job_AtharvaBhatkhalkar1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>This field is the name of the job.
User should not enter name but system should create it automatically.
The name should follow this format “JOB-{count}”. Count should be increased automatically for each new job posted(created). For. ex. JOB-001, JOB-002.</description>
    <displayFormat>JOB-{000}</displayFormat>
    <label>Name</label>
    <type>AutoNumber</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Number_of_Positions__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Positions__c</fullName>
    <description>This field indicates how many numbers of positions are available for this position
It should accept only numeric values up to 10 digits and not any text value.</description>
    <inlineHelpText>kindly enter the number of positions</inlineHelpText>
    <label>Number of Positions</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Qualification_Required__c.field-meta.xml
<CustomField>
    <fullName>Qualification_Required__c</fullName>
    <label>Qualification_Required</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Job_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Bcom</fullName>
            </value>
            <value>
                <fullName>MBA</fullName>
            </value>
            <value>
                <fullName>BBA</fullName>
            </value>
            <value>
                <fullName>BSC</fullName>
            </value>
            <value>
                <fullName>BTech.</fullName>
            </value>
            <value>
                <fullName>MSC</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Required_Skills__c.field-meta.xml
<CustomField>
    <fullName>Required_Skills__c</fullName>
    <label>Required_Skills</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Job_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>People Skills</fullName>
            </value>
            <value>
                <fullName>Team Player</fullName>
            </value>
            <value>
                <fullName>Self Management</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C++</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>.Net</fullName>
            </value>
            <value>
                <fullName>PHP</fullName>
            </value>
            <value>
                <fullName>Networking</fullName>
            </value>
            <value>
                <fullName>Linux</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Salary_Offered__c.field-meta.xml
<CustomField>
    <fullName>Salary_Offered__c</fullName>
    <description>This field indicates how much salary is offered for this job.
It should accept only numeric values up to 5 digits and not any text value.
Salary should be displayed in dollar format.</description>
    <label>Salary Offered</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

SalesforceTraining/force-app/main/default/classes/ViewJobController.cls
/********************************************************************** 
Name: ViewJobController 
Copyright © 2019 Enzigma Company Inc. 
====================================================== 
====================================================== 
Purpose: 
------- 
====================================================== 
====================================================== 
History 
------- 
VERSION AUTHOR DATE DETAIL FEATURES/CSR/TTP 
1.0 - Atharva Bhatkhalkar 03/04/2009 INITIAL DEVELOPMENT CSR: 
***********************************************************************/ 

public class ViewJobController {
/*******************************************************************
Purpose: Constructor which initializaes the memory for 
		object of list of candidate and the job object. 
********************************************************************/
   
     public ViewJobController() {
        objectOfJob=new Job_AtharvaBhatkhalkar__c();
        lstOfCanidateObject=new List<Candidate_AtharvaBhatkhalkar__c>();
    }
   
    public Job_AtharvaBhatkhalkar__c objectOfJob {get;set;}
    private List<Candidate_AtharvaBhatkhalkar__c> lstOfCanidateObject{get;set;}
    public list<Job_AtharvaBhatkhalkar__c> SearchVal {get;set;}
    
/*******************************************************************
Purpose: This method returns the list of candidate to the vfpage.
Returns: List of candidate.
********************************************************************/
    
    public List<Candidate_AtharvaBhatkhalkar__c> getCandObj() {
        return lstOfCanidateObject;
    }
/*******************************************************************
Purpose: To fetch the values from the database we use the get method.
Returns: This method returns the values of job object to the vfpage.
********************************************************************/
    
    public Job_AtharvaBhatkhalkar__c getjob() {
        return objectOfJob;
    }
/*******************************************************************
Purpose: This method searches for the values provided by the user from 
		vfpage which checks for the name of the job object and the 
		candidates who applied for that job.
********************************************************************/
    
    public void searchVal(){
        objectOfJob = [SELECT id, name, Name__c,Description__c,Number_of_Positions__c,Active__c,
               Salary_Offered__c,Manager__c,Job_Type__c,Required_Skills__c,Qualification_Required__c,
               Certification_Required__c
               FROM Job_AtharvaBhatkhalkar__c
               WHERE Name =: objectOfJob.Name];
        
        
        lstOfCanidateObject=[SELECT id, Name, First_Name__c,Last_Name__c,
                 Salutation__c,Date_of_Birth__c,Email__c,Country__c,
                 State__c,Application_Date__c,Status__c,Expected_Salary__c,
                 JOB__c FROM Candidate_AtharvaBhatkhalkar__c WHERE JOB__r.name =: objectOfJob.name ];
        
    }
}