SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/Candidate_AtharvaBhatkhalkar__c.object-meta.xml
<CustomObject>
    <description>Fields -
Following are the fields need to be created on object Candidate. A trainee will create the following fields with the mentioned Label name and appropriate data type. Also, refer to the Required field column for each field.</description>
    <label>Candidate_AtharvaBhatkhalkar</label>
    <nameField>
        <label>Candidate_AtharvaBhatkhalkar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate_AtharvaBhatkhalkar</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/Application_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Date__c</fullName>
    <description>It should accept date.</description>
    <inlineHelpText>kindly input the date</inlineHelpText>
    <label>Application Date</label>
    <type>Date</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Add a list of the following country: Australia, India, United States</description>
    <inlineHelpText>kindly select any</inlineHelpText>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth__c</fullName>
    <description>Should accept the</description>
    <inlineHelpText>kindly give the date of birth</inlineHelpText>
    <label>DOB</label>
    <type>Date</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>One should enter only valid email address</description>
    <inlineHelpText>kindly give your valid Email.</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/Expected_Salary__c.field-meta.xml
<CustomField>
    <fullName>Expected_Salary__c</fullName>
    <description>It should accept numerical value in dollar format</description>
    <label>Expected Salary</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Text field
Should only accept 15 characters.</description>
    <inlineHelpText>Kindly enter your first name here.</inlineHelpText>
    <label>First Name</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/JOB__c.field-meta.xml
<CustomField>
    <fullName>JOB__c</fullName>
    <description>It should be able to relate a candidate to a job</description>
    <label>Job_AtharvaBhatkhalkar</label>
    <referenceTo>Job_AtharvaBhatkhalkar__c</referenceTo>
    <relationshipLabel>Candidate_AtharvaBhatkhalkar</relationshipLabel>
    <relationshipName>Candidate_AtharvaBhatkhalkar</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Text field
Should only accept 15 characters.</description>
    <inlineHelpText>Kindly enter your last name.</inlineHelpText>
    <label>Last Name</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <description>It should have fixed values: ‘Mr.’, ‘Ms.’
A user should be able to select any one of the value.</description>
    <inlineHelpText>kindly select any one salutation from list</inlineHelpText>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Ms.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Victoria</fullName>
            </value>
            <value>
                <fullName>Western Australia</fullName>
            </value>
            <value>
                <fullName>Christmas Island</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Gujrat</fullName>
            </value>
            <value>
                <fullName>Madhyapradesh</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>User should be able to accept the value from this values : Applied, Interviewed, Reject, Hired.</description>
    <inlineHelpText>kindly select your status.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewed</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SalesforceTraining/force-app/main/default/classes/customControllerForCandidateComponent.cls
/********************************************************************** 
Name: customControllerForCandidateComponent 
Copyright © 2019 Enzigma Company Inc. 
====================================================== 
====================================================== 
Purpose: This class is written for the related list 
		componen which fetches the values from the 
		candidate object.
------- 
====================================================== 
====================================================== 
History 
------- 
VERSION AUTHOR DATE DETAIL FEATURES/CSR/TTP 
1.0 - Atharva Bhatkhalkar 03/04/2009 INITIAL DEVELOPMENT CSR: 
***********************************************************************/ 


public class customControllerForCandidateComponent{
    private Candidate_AtharvaBhatkhalkar__c objOfCandidateValues{get;set;}
    
 /*******************************************************************
Purpose: This method is a constructor which fetches the field values	
		of the candidate object after matching the id from the vfpage.
********************************************************************/
	 public customControllerForCandidateComponent() {
        objOfCandidateValues = [SELECT id, First_Name__c,Last_Name__c,Salutation__c,Date_of_Birth__c,Email__c,
                                Country__c,State__c,Application_Date__c,Status__c,Expected_Salary__c,JOB__c 
                                FROM Candidate_AtharvaBhatkhalkar__c
                                WHERE id = :ApexPages.currentPage().getParameters().get('id')];
    }
/*******************************************************************
Purpose: get method returns the values which he gets from the constructor
		in the objOfCandidateValues object.
Returns: The values of candidate object.
********************************************************************/
    
    public Candidate_AtharvaBhatkhalkar__c getobjOfCandidateValues() {
        return objOfCandidateValues;
    }
}