SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/Candidate_AtharvaBhatkhalkar__c.object-meta.xml
<CustomObject>
    <description>Fields -
Following are the fields need to be created on object Candidate. A trainee will create the following fields with the mentioned Label name and appropriate data type. Also, refer to the Required field column for each field.</description>
    <label>Candidate_AtharvaBhatkhalkar</label>
    <nameField>
        <label>Candidate_AtharvaBhatkhalkar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate_AtharvaBhatkhalkar</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/Application_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Date__c</fullName>
    <description>It should accept date.</description>
    <inlineHelpText>kindly input the date</inlineHelpText>
    <label>Application Date</label>
    <type>Date</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>One should enter only valid email address</description>
    <inlineHelpText>kindly give your valid Email.</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/Expected_Salary__c.field-meta.xml
<CustomField>
    <fullName>Expected_Salary__c</fullName>
    <description>It should accept numerical value in dollar format</description>
    <label>Expected Salary</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/JOB__c.field-meta.xml
<CustomField>
    <fullName>JOB__c</fullName>
    <description>It should be able to relate a candidate to a job</description>
    <label>Job_AtharvaBhatkhalkar</label>
    <referenceTo>Job_AtharvaBhatkhalkar__c</referenceTo>
    <relationshipLabel>Candidate_AtharvaBhatkhalkar</relationshipLabel>
    <relationshipName>Candidate_AtharvaBhatkhalkar</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/Job_AtharvaBhatkhalkar__c.object-meta.xml
<CustomObject>
    <description>Fields -
Following are the fields need to be created on object Job. A trainee will create the following fields with the mentioned Label name and appropriate data type.</description>
    <label>Job_AtharvaBhatkhalkar</label>
    <nameField>
        <label>Job_AtharvaBhatkhalkar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_AtharvaBhatkhalkar</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field should have only two either or values (true/false)
If it has one value it means a job is active
If it has another value it means a job is not active</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Hired_Applicants__c.field-meta.xml
<CustomField>
    <fullName>Hired_Applicants__c</fullName>
    <description>This field indicates the count of the total Hired candidate has applied to this job.
It should be a numeric field and must be calculated automatically as any candidate is hired for a job( Candidate status = ‘Hired’);</description>
    <label>Hired Applicants</label>
    <summaryFilterItems>
        <field>Candidate_AtharvaBhatkhalkar__c.Status__c</field>
        <operation>equals</operation>
        <value>Hired</value>
    </summaryFilterItems>
    <summaryForeignKey>Candidate_AtharvaBhatkhalkar__c.JOB__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Number_of_Positions__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Positions__c</fullName>
    <description>This field indicates how many numbers of positions are available for this position
It should accept only numeric values up to 10 digits and not any text value.</description>
    <inlineHelpText>kindly enter the number of positions</inlineHelpText>
    <label>Number of Positions</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SalesforceTraining/force-app/main/default/classes/CandidateTriggerHandler.cls
/********************************************************************** 
Name: CandidateTriggerHandler 
Copyright © 2019 Enzigma Company Inc. 
====================================================== 
====================================================== 
Purpose: This class is designed to control all the activities
of the triggers.
------- 
====================================================== 
====================================================== 
History 
------- 
VERSION AUTHOR DATE DETAIL FEATURES/CSR/TTP 
1.0 - Atharva Bhatkhalkar 03/04/2009 INITIAL DEVELOPMENT CSR: 
***********************************************************************/ 

public class CandidateTriggerHandler {
    
    Set<id> setOfId = new Set<id>();
/*******************************************************************
Purpose: This method gets the value of Expected_salary field from 
the trigger.new context variable and checks that is is not null
if it is null then using addError() it gives the error message.
Parameters: list of trigger.new
********************************************************************/
    
    
    public void expectedSalaryMissing(List<Candidate_AtharvaBhatkhalkar__c> lstOfCandidateInTrigger){
        
        for(Candidate_AtharvaBhatkhalkar__c objCandidate : lstOfCandidateInTrigger){
            setOfId.add(objCandidate.Job__c);
            if (objCandidate.Expected_Salary__c == null) {
                objCandidate.addError('Expected Salary field is missing');     
            }
        }
    }
    
/*******************************************************************
Purpose: This method checks that the job which candidate has applied is 
		inactive and gives the specific error.
Parameters: list of trigger.new
********************************************************************/

    public void inactiveJobApplied(List<Candidate_AtharvaBhatkhalkar__c> lstOfCandidateInTrigger){ 
         for(Candidate_AtharvaBhatkhalkar__c objCandidate : lstOfCandidateInTrigger){
             setOfId.add(objCandidate.Job__c);}
        map<Id,Job_AtharvaBhatkhalkar__c> mapJobs = new map<Id,Job_AtharvaBhatkhalkar__c>(
            [SELECT id,Active__c FROM Job_AtharvaBhatkhalkar__c WHERE id in :setOfId]
        );
        
        for(Candidate_AtharvaBhatkhalkar__c candidate : lstOfCandidateInTrigger){
            if(mapJobs.get(candidate.JOB__c).Active__c == false){
                candidate.addError('Applied job is inactive');
            }
        }        
    }
    
/*******************************************************************
Purpose: This method swaps the date with created date with the date 
		applied by the respective candidate. 
Parameters: list of trigger.new
********************************************************************/
    public void givenDateSwapBycreatedDate(List<Candidate_AtharvaBhatkhalkar__c> lstOfCandidateOfAftTrig){
        List<Candidate_AtharvaBhatkhalkar__c> lstOfCandidate = new List<Candidate_AtharvaBhatkhalkar__c>();
        for(Candidate_AtharvaBhatkhalkar__c itrCandidate : lstOfCandidateOfAftTrig){
            Candidate_AtharvaBhatkhalkar__c objCandidate = new Candidate_AtharvaBhatkhalkar__c (Id = itrCandidate.Id);
            objCandidate.Application_Date__c=Date.parse(objCandidate.CreatedDate.date().format());
            lstOfCandidate.add(objCandidate);
        }
        update lstOfCandidate;
}
    
    
/*******************************************************************
Purpose: This method sends email to respective candidate if the status 
		changes to hired
Parameters: list of trigger.new
********************************************************************/
public void sendEmail(List<Candidate_AtharvaBhatkhalkar__c> lstOfCandidateAfterInsertOrUpdate){
        Set<Id> setOfIdz= new Set<Id>();
        
        List<Messaging.SingleEmailMessage> lstOfMails = new List<Messaging.SingleEmailMessage>();
        
        for(Candidate_AtharvaBhatkhalkar__c itrOfCandidate : lstOfCandidateAfterInsertOrUpdate){
            setOfIdz.add(itrOfCandidate.JOB__c);
            if(itrOfCandidate.Email__c!=null){
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                List<String> sendTo = new List<String>();
                sendTo.add(itrOfCandidate.Email__c);
                mail.setToAddresses(sendTo);
                mail.setSubject('Important Notice ' + itrOfCandidate.LastModifiedDate);
                String strBody = 'All required candidate has been hired for this job on ';
                mail.setHtmlBody(strBody);
                lstOfMails.add(mail);
            }
        }
        Messaging.sendEmail(lstOfMails);
}
    
/*******************************************************************
Purpose: This method sets the status to inactive if the hired applicants
		number is equivalent to the number of positions.
Parameters: list of trigger.new
Returns: [optional]
Throws [Exceptions]: [optional]
********************************************************************/
   public void setStatusToInactive(List<Candidate_AtharvaBhatkhalkar__c> lstOfCandidateAfterInsertOrUpdate){
         for(Candidate_AtharvaBhatkhalkar__c objCandidate : lstOfCandidateAfterInsertOrUpdate){
             setOfId.add(objCandidate.Job__c);}
       
        List<Job_AtharvaBhatkhalkar__c> lstOfJobGlobal = new  List<Job_AtharvaBhatkhalkar__c>();
        List<Job_AtharvaBhatkhalkar__c> lstOfJobAppField= new List<Job_AtharvaBhatkhalkar__c>();
        
        lstOfJobAppField = [SELECT Active__c, Hired_Applicants__c, Number_of_Positions__c 
                            FROM Job_AtharvaBhatkhalkar__c WHERE Id in :setOfId];
        for(Job_AtharvaBhatkhalkar__c itrJob : lstOfJobAppField){
            if(itrJob.Hired_Applicants__c == itrJob.Number_of_Positions__c - 1){
                itrJob.Active__c=false;
                lstOfJobGlobal.add(itrJob);
            }
        }
        update lstOfJobGlobal;
    }
    
}