SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/Candidate_AtharvaBhatkhalkar__c.object-meta.xml
<CustomObject>
    <description>Fields -
Following are the fields need to be created on object Candidate. A trainee will create the following fields with the mentioned Label name and appropriate data type. Also, refer to the Required field column for each field.</description>
    <label>Candidate_AtharvaBhatkhalkar</label>
    <nameField>
        <label>Candidate_AtharvaBhatkhalkar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate_AtharvaBhatkhalkar</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>One should enter only valid email address</description>
    <inlineHelpText>kindly give your valid Email.</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Text field
Should only accept 15 characters.</description>
    <inlineHelpText>Kindly enter your first name here.</inlineHelpText>
    <label>First Name</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/JOB__c.field-meta.xml
<CustomField>
    <fullName>JOB__c</fullName>
    <description>It should be able to relate a candidate to a job</description>
    <label>Job_AtharvaBhatkhalkar</label>
    <referenceTo>Job_AtharvaBhatkhalkar__c</referenceTo>
    <relationshipLabel>Candidate_AtharvaBhatkhalkar</relationshipLabel>
    <relationshipName>Candidate_AtharvaBhatkhalkar</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Text field
Should only accept 15 characters.</description>
    <inlineHelpText>Kindly enter your last name.</inlineHelpText>
    <label>Last Name</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Candidate_AtharvaBhatkhalkar__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>User should be able to accept the value from this values : Applied, Interviewed, Reject, Hired.</description>
    <inlineHelpText>kindly select your status.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Interviewed</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SalesforceTraining/force-app/main/default/classes/Practice_Class.cls
public class Practice_Class {
	
    public void Practice_Class(){
     List<Candidate_AtharvaBhatkhalkar__c> lstOfCandidate_AtharvaBhatkhalkar = [SELECT id, Name,First_Name__c,
                                                      Last_Name__c,Email__c,Status__c, JOB__c 
                                                      FROM Candidate_AtharvaBhatkhalkar__c LIMIT 100];
    
    List<Candidate_AtharvaBhatkhalkar__c> lstOfCandidate_AtharvaBhatkhalakarForInsert = new List<Candidate_AtharvaBhatkhalkar__c>();

	for(Candidate_AtharvaBhatkhalkar__c objOfCandidate : lstOfCandidate_AtharvaBhatkhalkar)
    {
        objOfCandidate.Name='New candidate';
        objOfCandidate.First_Name__c='Ramesh';
        objOfCandidate.Last_Name__c='sharma';
        objOfCandidate.Email__c='ok@ok.com';
        objOfCandidate.Status__c='Applied';
        objOfCandidate.JOB__c='DevOps';
        lstOfCandidate_AtharvaBhatkhalakarForInsert.add(objOfCandidate);
    }
   }
}