SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/Job_AtharvaBhatkhalkar__c.object-meta.xml
<CustomObject>
    <description>Fields -
Following are the fields need to be created on object Job. A trainee will create the following fields with the mentioned Label name and appropriate data type.</description>
    <label>Job_AtharvaBhatkhalkar</label>
    <nameField>
        <label>Job_AtharvaBhatkhalkar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_AtharvaBhatkhalkar</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field should have only two either or values (true/false)
If it has one value it means a job is active
If it has another value it means a job is not active</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>This field should accept bold text, italic text, underline text, images.</description>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field indicates the relation of job record to the Contact record.</description>
    <label>Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job_AtharvaBhatkhalkar</relationshipLabel>
    <relationshipName>Job_AtharvaBhatkhalkar1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Number_of_Positions__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Positions__c</fullName>
    <description>This field indicates how many numbers of positions are available for this position
It should accept only numeric values up to 10 digits and not any text value.</description>
    <inlineHelpText>kindly enter the number of positions</inlineHelpText>
    <label>Number of Positions</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Qualification_Required__c.field-meta.xml
<CustomField>
    <fullName>Qualification_Required__c</fullName>
    <label>Qualification_Required</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Job_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Bcom</fullName>
            </value>
            <value>
                <fullName>MBA</fullName>
            </value>
            <value>
                <fullName>BBA</fullName>
            </value>
            <value>
                <fullName>BSC</fullName>
            </value>
            <value>
                <fullName>BTech.</fullName>
            </value>
            <value>
                <fullName>MSC</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SalesforceTraining/force-app/main/default/classes/TestMethodForJobDeleteTrigger.cls
@isTest
public class TestMethodForJobDeleteTrigger {

    @isTest
    static void deleteJobWhenActiveFalse(){
        Contact objContact = new Contact(LastName='Test-Enzigma-Contact');
        insert objContact;
        system.assertNotEquals(objContact.id, null);
        
        Job_AtharvaBhatkhalkar__c objJob = new Job_AtharvaBhatkhalkar__c(Name = 'Ramesh',
                                                                       Description__c = 'Hello world',
                                                                       Number_of_Positions__c = 2,
                                                                       Active__c = true,
                                                                       Manager__c = objContact.Id,
                                                                       Qualification_Required__c = 'Bcom'
                                                                      );        
        try {
            insert objJob;
            Job_AtharvaBhatkhalkar__c objJobQuery = [SELECT id FROM Job_AtharvaBhatkhalkar__c WHERE id =: objJob.Id];
            system.assertNotEquals(objJobQuery.Id, null);
            delete objJobQuery;
            
        }catch(Exception e){
            System.assert(e.getMessage().contains('This Job is active and can not be deleted'));
        }       
    }   
}