SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/Job_AtharvaBhatkhalkar__c.object-meta.xml
<CustomObject>
    <description>Fields -
Following are the fields need to be created on object Job. A trainee will create the following fields with the mentioned Label name and appropriate data type.</description>
    <label>Job_AtharvaBhatkhalkar</label>
    <nameField>
        <label>Job_AtharvaBhatkhalkar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_AtharvaBhatkhalkar</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field should have only two either or values (true/false)
If it has one value it means a job is active
If it has another value it means a job is not active</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Certification_Required__c.field-meta.xml
<CustomField>
    <fullName>Certification_Required__c</fullName>
    <label>Certification_Required</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Job_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>PMP (Project Management        Professional)</fullName>
            </value>
            <value>
                <fullName>CMP (Certified Project Manager)</fullName>
            </value>
            <value>
                <fullName>MPM (Master Project Manager)</fullName>
            </value>
            <value>
                <fullName>Sun Certified</fullName>
            </value>
            <value>
                <fullName>SAS</fullName>
            </value>
            <value>
                <fullName>ORACLE</fullName>
            </value>
            <value>
                <fullName>Sybase</fullName>
            </value>
            <value>
                <fullName>Microsoft</fullName>
            </value>
            <value>
                <fullName>CISCO</fullName>
            </value>
            <value>
                <fullName>RedHat</fullName>
            </value>
            <value>
                <fullName>IBM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>This field should accept bold text, italic text, underline text, images.</description>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Developer</fullName>
            </value>
            <value>
                <fullName>Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Manager__c.field-meta.xml
<CustomField>
    <fullName>Manager__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field indicates the relation of job record to the Contact record.</description>
    <label>Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Job_AtharvaBhatkhalkar</relationshipLabel>
    <relationshipName>Job_AtharvaBhatkhalkar1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>This field is the name of the job.
User should not enter name but system should create it automatically.
The name should follow this format “JOB-{count}”. Count should be increased automatically for each new job posted(created). For. ex. JOB-001, JOB-002.</description>
    <displayFormat>JOB-{000}</displayFormat>
    <label>Name</label>
    <type>AutoNumber</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Number_of_Positions__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Positions__c</fullName>
    <description>This field indicates how many numbers of positions are available for this position
It should accept only numeric values up to 10 digits and not any text value.</description>
    <inlineHelpText>kindly enter the number of positions</inlineHelpText>
    <label>Number of Positions</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Qualification_Required__c.field-meta.xml
<CustomField>
    <fullName>Qualification_Required__c</fullName>
    <label>Qualification_Required</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Job_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Bcom</fullName>
            </value>
            <value>
                <fullName>MBA</fullName>
            </value>
            <value>
                <fullName>BBA</fullName>
            </value>
            <value>
                <fullName>BSC</fullName>
            </value>
            <value>
                <fullName>BTech.</fullName>
            </value>
            <value>
                <fullName>MSC</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Required_Skills__c.field-meta.xml
<CustomField>
    <fullName>Required_Skills__c</fullName>
    <label>Required_Skills</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Job_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>People Skills</fullName>
            </value>
            <value>
                <fullName>Team Player</fullName>
            </value>
            <value>
                <fullName>Self Management</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C++</fullName>
            </value>
            <value>
                <fullName>Java</fullName>
            </value>
            <value>
                <fullName>.Net</fullName>
            </value>
            <value>
                <fullName>PHP</fullName>
            </value>
            <value>
                <fullName>Networking</fullName>
            </value>
            <value>
                <fullName>Linux</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Salary_Offered__c.field-meta.xml
<CustomField>
    <fullName>Salary_Offered__c</fullName>
    <description>This field indicates how much salary is offered for this job.
It should accept only numeric values up to 5 digits and not any text value.
Salary should be displayed in dollar format.</description>
    <label>Salary Offered</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

SalesforceTraining/force-app/main/default/classes/controllerOfJob_AtharvaBhatkhalkar.cls
/********************************************************************** 
Name: controllerOfJob_AtharvaBhatkhalkar
Copyright © 2019 Enzigma Company Inc. 
====================================================== 
====================================================== 
Purpose: Custom controller of Job object which fetches 
		values from vfpage.
------- 
====================================================== 
====================================================== 
History 
------- 
VERSION AUTHOR DATE DETAIL FEATURES/CSR/TTP 
1.0 - Atharva Bhatkhalkar 03/04/2009 INITIAL DEVELOPMENT CSR:
***********************************************************************/ 

public class controllerOfJob_AtharvaBhatkhalkar {
    
    private Job_AtharvaBhatkhalkar__c objOfJob_Atharva{get;set;}
    
/*******************************************************************
Purpose: This is a constructor which gets all the values from job 
		object where the id is equal.
********************************************************************/
	public void controllerOfJob_AtharvaBhatkhalkar() {
        objOfJob_Atharva = [SELECT id, Name__c,Description__c,Number_of_Positions__c,Active__c,Salary_Offered__c,Manager__c,Job_Type__c,Required_Skills__c,Qualification_Required__c	,Certification_Required__c FROM Job_AtharvaBhatkhalkar__c
               WHERE id = :ApexPages.currentPage().getParameters().get('id')];
    }
    
    
/*******************************************************************
Purpose: To Get the required value from the database.
Returns: The data to the vfPage.
********************************************************************/
    public Job_AtharvaBhatkhalkar__c getobjOfJob_Atharva() {
        return objOfJob_Atharva;
    }
    
    
/*******************************************************************
Purpose: This method is called from vfpage and which saves the value
		to the database.
Returns: Returns to the view state after saving the record.
********************************************************************/
	public PageReference save() {
        upsert objOfJob_Atharva;
        PageReference pref = new ApexPages.StandardController(objOfJob_Atharva).view();
        return pref;
    }
    
}