SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/Job_AtharvaBhatkhalkar__c.object-meta.xml
<CustomObject>
    <description>Fields -
Following are the fields need to be created on object Job. A trainee will create the following fields with the mentioned Label name and appropriate data type.</description>
    <label>Job_AtharvaBhatkhalkar</label>
    <nameField>
        <label>Job_AtharvaBhatkhalkar Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job_AtharvaBhatkhalkar</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field should have only two either or values (true/false)
If it has one value it means a job is active
If it has another value it means a job is not active</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Hired_Applicants__c.field-meta.xml
<CustomField>
    <fullName>Hired_Applicants__c</fullName>
    <description>This field indicates the count of the total Hired candidate has applied to this job.
It should be a numeric field and must be calculated automatically as any candidate is hired for a job( Candidate status = ‘Hired’);</description>
    <label>Hired Applicants</label>
    <summaryFilterItems>
        <field>Candidate_AtharvaBhatkhalkar__c.Status__c</field>
        <operation>equals</operation>
        <value>Hired</value>
    </summaryFilterItems>
    <summaryForeignKey>Candidate_AtharvaBhatkhalkar__c.JOB__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

SalesforceTraining/force-app/main/default/objects/Job_AtharvaBhatkhalkar__c/fields/Number_of_Positions__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Positions__c</fullName>
    <description>This field indicates how many numbers of positions are available for this position
It should accept only numeric values up to 10 digits and not any text value.</description>
    <inlineHelpText>kindly enter the number of positions</inlineHelpText>
    <label>Number of Positions</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SalesforceTraining/force-app/main/default/classes/JobTriggerHandler.cls
/********************************************************************** 
Name: JobTriggerHandler 
Copyright © 2009 ABC Company Inc. 
====================================================== 
====================================================== 
Purpose: This class checks the trigger events on Job 
Object.
------- 
====================================================== 
====================================================== 
History 
------- 
VERSION AUTHOR DATE DETAIL FEATURES/CSR/TTP 
1.0 - Atharva Bhatkhalkar 03/04/2009 INITIAL DEVELOPMENT CSR:  
***********************************************************************/ 
public class JobTriggerHandler {
    
    
    /*******************************************************************
Purpose: This method checks that if the job status is active then it 
cannot be deleted.
Parameters: list of trigger.new
********************************************************************/
    
    public void JobActiveCannotBeDeleted(List<Job_AtharvaBhatkhalkar__c> lstOfJobTrigger){
        for (Job_AtharvaBhatkhalkar__c objJob :lstOfJobTrigger){
            if(objJob.Active__c) {
                objJob.addError('This Job is active and can not be deleted');
            }
        }
    }
    
    
    /*******************************************************************
Purpose: This method checks that if the number of positions becomes 
greater than hired applicants then it changes the status of active 
to true.
Parameters: trigger.new
********************************************************************/
    
    public void JobStatusToActive(List<Job_AtharvaBhatkhalkar__c> lstOfJobTriggerActive){
        List<Job_AtharvaBhatkhalkar__c> lstOfJobForStatusActive = [SELECT id,Number_of_Positions__c,Hired_Applicants__c,Active__c 
                                                                   FROM Job_AtharvaBhatkhalkar__c WHERE id in : lstOfJobTriggerActive];
        List<Job_AtharvaBhatkhalkar__c> lstForUpdate = new List<Job_AtharvaBhatkhalkar__c>();
        for(Job_AtharvaBhatkhalkar__c objOfJob:lstOfJobForStatusActive){
            if(objOfJob.Number_of_Positions__c > objOfJob.Hired_Applicants__c){
              objOfJob.Active__c=true;
              lstForUpdate.add(objOfJob);
            }
        }
        update lstForUpdate;
    }
}